//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int RoleId { get; set; }
        public string Rolename { get; set; }
        public Nullable<int> Id { get; set; }
    
        public virtual tblRegistration tblRegistration { get; set; }
    }
}
